подключил стихи и шрифты
DunaevViktor/PoetryPortal pull request #13
Opened 2019-01-30 18:20 UTC by DunaevViktor

https://github.com/DunaevViktor/PoetryPortal/issues/12

2019-01-30 19:09 UTC, r-karol requested changes

2019-01-30 19:09 UTC, 5wag commented on public/index.html
> +    <link rel='stylesheet' href='./bootstrap.min.css'>
1. Чтобы было везде одинаково давай значение атрибута в двойных кавычках писать.
2. `./bootstrap.min.css` - так тоже правильно, но, опять же, чтобы было везде одинаково давай лучше сделаем `%PUBLIC_URL%/bootstrap.min.css`

2019-01-30 19:30 UTC, r-karol approved these changes

2019-01-30 20:45 UTC, merged

2019-01-31 08:40 UTC, Vlad160 commented on public/index.html
> +    <link rel="tylesheet" href="%PUBLIC_URL%/bootstrap.min.css" />
Что-то новое "tylesheet" 👍 
Вообще говоря, лучше подключать с cdn, чтобы не держать локально зависимости. Благо cdn поддерживает версионирование. Но есть второй вариант, как по мне он лучше. Исталим бутстрап как обычно ```npm i bootstrap```. И импортируем его либо в index.js, либо в App.js. 
Просто
```import 'bootstrap/dist/css/bootstrap.min.css';```
Тогда мы имеем четкую и явную зависимость.
Но тут конечно дело вкуса.