header v 1.0
DunaevViktor/PoetryPortal pull request #27
Opened 2019-02-19 16:03 UTC by DunaevViktor

https://github.com/DunaevViktor/PoetryPortal/issues/22

2019-02-19 21:12 UTC, r-karol reviewed
Я, конечно, не могу запретить тебе писать свои стили, хочешь писать - пиши. Твои стили тебе понадобились потому что ты разметку кривую сделал. Попробуй сделай окошко поменьше, или вообще включи просмотр с телефона, там все ломается и полная жесть, кровь, кишки. Мой совет: зайди на [эту](https://getbootstrap.com/docs/3.3/components/#navbar) страничку, найди то что похоже на то что тебе надо, полностью скопируй и поправь под себя.

2019-02-19 21:12 UTC, r-karol commented on src/components/Header.js
> +const arrayOfLinks = {
Во-первых, это не массив. Во-вторых, просто Links

2019-02-19 21:12 UTC, 5wag commented on src/components/Header.js
> +            <form action={arrayOfLinks.main_page}>
Не надо помещать каждую кнопку в форму. Форма это форма, кнопка это кнопка. Кнопка может жить сама по себе, ей форма не нужна.

2019-02-19 21:12 UTC, 5wag commented on src/components/Header.js
> +              <button
Можно, конечно, и кнопки, но по смыслу это ссылки, а для ссылок используется другой тег.

2019-02-19 21:12 UTC, 5wag commented on src/components/Header.js
> +              <button
В остальных местах то же самое

2019-02-19 21:12 UTC, 5wag commented on src/components/Header.js
> +            <form action={arrayOfLinks.main_page}>
В остальных местах то же самое

2019-02-20 08:02 UTC, Vlad160 commented on src/App.js
> +    return <Header/>
На будущее: если делаешь наперед, то и ветки создавай от последней созданной. Т.е. ты создал ветку, где сделал `Footer`, а потом делаешь `Header`. Так и создай ветку с хидером, от ветки футера. Потом проблем будет меньше

2019-02-20 08:06 UTC, Vlad160 commented on src/components/Header.js
> +  poetry_portal: "#",
А чего с подчеркиванием переменные?

2019-02-25 19:15 UTC, 5wag commented on src/components/Header.js
> +      </div>
Все четко только `header` верни. Раз у твоей странички есть хедер, то надо `header`.

2019-02-25 19:16 UTC, r-karol requested changes
Верни `header` чтобы на страничке был этот тег. Заверни свою разметку в `header` (или попробуй вместо дива самого верхнего, `header` никакого стилизования своего не имеет насколько я знаю)

2019-02-25 20:29 UTC, 5wag commented
Резолвни конфликты (пиши, если нужна помощь), потом я апрувну (если ничо не поломаешь :)). Кстати, когда будешь резолвать у тебя уже появится в твоей ветке с хедером ссылки из задания про роутер, так что можешь сразу ссылки в хедере поменять на правильные (роутеровские)

2019-02-25 20:30 UTC, Vlad160 submitted a review, later dismissed

2019-02-25 22:13 UTC, r-karol requested changes
Исправь `a` на `Link`

2019-02-25 22:13 UTC, 5wag commented on src/components/Header.js
> +                  <a href={LINKS.mainPage}>Главная</a>
Отэта должно быть `Link` (помнишь почему?)
И дальше по тексту тоже

2019-02-25 22:13 UTC, 5wag commented on src/components/Header.js
> +                  <a href={LINKS.mainPage}>Главная</a>
Попробуй вот как сейчас со ссылками потыкай по ссылкам в хедере, и попробуй с `Link`
Обрати внимание что страничка (хедер) не перерисовывается

2019-02-26 09:46 UTC, Vlad160 approved these changes

2019-02-26 12:09 UTC, r-karol approved these changes

2019-02-26 12:28 UTC, merged