footer v 0.1
DunaevViktor/PoetryPortal pull request #28
Opened 2019-02-19 16:04 UTC by DunaevViktor

https://github.com/DunaevViktor/PoetryPortal/issues/24

2019-02-19 21:29 UTC, r-karol reviewed
Поправь разметку (удали формы, поправь ссылки). Компонента очень простая и кода должно быть мало, а у тебя тут целое полотно. [Вот](https://css-tricks.com/couple-takes-sticky-footer/) несколько примеров как сделать так чтобы футер уезжал вниз если не заполнена страничка, посмотри, выбери что тебе больше нравится, РАЗБЕРИСЬ КАК РАБОТАЕТ, и сделай так же.
З.Ы. я бы еще сделал чтобы ссылки в новой вкладке открывались

2019-02-19 21:29 UTC, 5wag commented on public/index.html
> +    <script src="https://use.fontawesome.com/f907eb0db2.js"></script>
Это точно нужно?

2019-02-19 21:29 UTC, 5wag commented on src/components/Footer.js
> +const arrayOfLinks = {
Links

2019-02-19 21:29 UTC, 5wag commented on src/components/Footer.js
> +      <form action={arrayOfLinks.facebook}>
Не нужно каждую кнопку в форму пихать.

2019-02-19 21:29 UTC, 5wag commented on src/components/Footer.js
> +        <button type="submit" className="btn btn-light footer-button-float">
Это ссылки, ссылки - это другой тег

2019-02-19 21:29 UTC, 5wag commented on src/components/Footer.js
> +          <i class="fab fa-instagram fa-3x" />
Проверь что у тебя в консоли

2019-02-19 21:29 UTC, 5wag commented on src/components/Footer.js
> +    <footer id="poetry-portal-footer">
Для стилей принято использовать классы. Айдишки используют для функционала не связанного со стилями (это можно, но негласная договоренность говорит что не стоит)

2019-02-20 07:47 UTC, Vlad160 commented on src/components/Footer.js
> +      <form action={arrayOfLinks.facebook}>
Да и вообще не нужна тут форма

2019-02-20 07:55 UTC, Vlad160 commented on src/components/Footer.js
> +};
Мне не очень нравится эта реализация. Допустим, тебе надо добавить новую линку. Твои действия:
* Дописать её сюда
* Дописать её обработку в компненте футера

Давай попробуем сделать немного по-другому. У тебя для каждой линки специфичным являются стили и сама линка, тогда можно попробовать это вынести выше. Сделай свои линки действительно массивом объектов с полями `name`, `link`, `styles`. А в компоненте просто в цикле отрисуй.

2019-02-20 07:58 UTC, Vlad160 commented on src/components/Footer.js
> +const arrayOfLinks = {
Рома верно заметил. Называй переменные правильно. Есть ещё такой момент, что код должен быть самодокументируемым, т.е. по названию переменной, функции и т.д. должно быть понятно её предназначение. Но и переусердствовать не стоит. По переменной `Links` вполне понятно, что это массив (окончание `s`), а вот `arrayOfLinks ` это уже оверкил.

2019-02-25 15:42 UTC, Vlad160 commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById("foot"));
Пожалуйста не надо. `App` это `точка входа` в приложение. `Рисуй` футер в `App`
```
// App.js

render() {
    <div>
        <Header/>
        <main> Content here </main>
        <Footer/>  <----------
    </div>
}

```

2019-02-25 15:43 UTC, Vlad160 commented on src/components/Footer.js
> +      list.push(
Пожалуйста, используй методы массива по назначению. Тут очень хорошо смотрится `links.map(...)`

2019-02-25 15:44 UTC, Vlad160 commented on src/components/Footer.js
> +const Links = [
Naming convention. Переменные либо camelCase. Такого рода константы можно капсом

2019-02-25 15:44 UTC, Vlad160 commented on src/components/Footer.js
> +          rel="noopener noreferrer"
В курсе зачем это?)

2019-02-25 17:14 UTC, 5wag commented on src/components/Footer.js
> +const Links = [
А мне нравится с большой буквы

2019-02-25 17:16 UTC, DunaevViktor commented on src/components/Footer.js
> +          rel="noopener noreferrer"
Чтобы новая вкладка не могла управлять родительской, а это нужно для безопасности.

2019-02-25 17:17 UTC, 5wag commented on src/components/Footer.js
> +          rel="noopener noreferrer"
Шок контент кста

2019-02-25 19:21 UTC, r-karol requested changes
Используй тег `footer`. Попробуй вместо дива, если не получится - заверни все в `footer`.

2019-02-25 19:21 UTC, r-karol commented on src/components/Footer.js
> +    return <div>{list}</div>;
Я бы воспользовался `footer` вместо `div`.

2019-02-25 19:21 UTC, r-karol commented on src/components/Footer.js
> +    return <div>{list}</div>;
Или див внутри футера если без дива никак

2019-02-25 19:29 UTC, 5wag commented on src/App.js
> +      <div class="app-body">
`class`. Всегда с открытой консолью в браузере работай. Там ошибочка красная

2019-02-25 20:07 UTC, Vlad160 commented on src/components/Footer.js
> +const Links = [
Не надо из других языков притаскивать какие-то правила именования и т.д. Тут так не делают. Если все будут делать как нравится, то потом вообще ничего понятно не будет

2019-02-25 20:08 UTC, Vlad160 commented on src/components/Footer.js
> +    return <div>{list}</div>;
Именно. Футер, это футер. Читаем про a11y

2019-02-25 20:23 UTC, Vlad160 commented on src/components/Footer.js
> +    const list = LINKS.map(function(LINKS) {
Так. Тут ты забавно придумал. 
1) Не очень хорошо юзать одно и тоже имя для переменной, по которой итерируемся, и текущему объекту. Эта функция маленькая, тут ещё пока понятно. Теперь представь, что функция больше. Ещё ты не сможешь обратиться к массиву ссылок из этой функции.
2) Давай все же писать в es6 стиле. 
```
LINKS.map(link => 
// Тело функции
)
```
выглядит чуть проще и нагляднее. https://learn.javascript.ru/es-function
3) Немного подумаем. Зачем тебе это дополнительное поле id? id - уникальный идентификатор, по которому реакт будет следить за объектами массива. Но разве у тебя у объекта ссылки уже нет поля с таким же смыслом?

2019-02-25 20:26 UTC, Vlad160 commented on src/components/Footer.js
> +    const list = LINKS.map(function(LINKS) {
К 3). Ты уже как-то обжегся с использованием индекса как `key`. Но давай вспомним в чем там была проблема. Там данные менялись. А тут будут меняться? Этот комментарий просто для разъяснения, хотел бы увидеть решение, основанное на предыдущем комменте.

2019-02-25 20:26 UTC, 5wag commented on src/components/Footer.js
> +    const list = LINKS.map(function(LINKS) {
Поля с таким же смыслом (уникальный идентификатор)

2019-02-25 22:18 UTC, r-karol approved these changes
Красава, мержи

2019-02-25 22:21 UTC, merged