router v 0.1
DunaevViktor/PoetryPortal pull request #29
Opened 2019-02-19 16:06 UTC by DunaevViktor

https://github.com/DunaevViktor/PoetryPortal/issues/25

2019-02-19 21:52 UTC, r-karol requested changes
По комментариям работай

2019-02-19 21:52 UTC, 5wag commented on src/App.js
> +        <RouteHeader />
Так, 
1. RouteHeader удаляем, вместо него будет твой header из другого пул реквеста, зачем нам мусор добавлять? Ты эту компоненту создал, попробовал, роутер работает, комитать его не надо, он не нужен.
2. Зачем этот див вокруг? Он, конечно, вроде как ничего не ломает, но тогда что уж, давай в 30 дивов завернем, все равно ничего не меняется.

2019-02-19 21:52 UTC, 5wag commented on src/Main.js
> +          <Route exact path="/" component={MainPosts} />
Я бы все роуты вынес в константу в отдельный файл. Чтобы там где я буду создавать `Link` мне не копировать строчки, а брать из константы. И если я захочу роут поменять, то меняю строчку в константе, и все, красота

2019-02-19 21:52 UTC, 5wag commented on src/RouteHeader.js
> +export default Header;
Это все удаляем, мусор не комитаем

2019-02-19 21:52 UTC, 5wag commented on src/pages/MainPosts.js
> +class MainPosts extends Component {
Я бы переименовал просто в Posts. У нас нет никаких кроме Main постов, так что это лишнее, но это дело вкуса

2019-02-20 08:09 UTC, Vlad160 commented on src/Main.js
> +          <Route exact path="/" component={MainPosts} />
А чего роутер не в `App` компоненте?

2019-02-25 17:53 UTC, r-karol submitted a review, later dismissed
Я апрувнул, мои просьбы не критичны, чисто косметика, на твое усмотрение

2019-02-25 17:53 UTC, 5wag commented on src/App.js
> +import Posts from "./pages/Posts";
Давай немного наведем красоту. Чтобы этот файлик импортами не засорять в папке `pages` создай файлик `index.js`, в который импортни все странички и сделай экспорт так чтобы тут я написал
```
import pages from "./pages/index"
```
 а дальше использовал `pages.Posts` и т.д.

2019-02-25 17:53 UTC, 5wag commented on src/route.js
> +    aboutMe: "/aboutme"
Давай сделаем `about-me`. Так намного красивее и читабельнее

2019-02-25 19:34 UTC, r-karol approved these changes
Красиво!

2019-02-25 19:47 UTC, 5wag commented
Можно мержить

2019-02-25 20:06 UTC, merged

2019-02-25 20:11 UTC, Vlad160 commented
На самом деле, лучше роуты делать массивом объектов. Подумайте о добавлении роутов или их каком-то изменении