создал apiService
DunaevViktor/PoetryPortal pull request #34
Opened 2019-02-27 17:13 UTC by DunaevViktor

Нужна помощь с промисом
https://github.com/DunaevViktor/PoetryPortal/issues/30

2019-02-27 22:28 UTC, r-karol requested changes
Оставил комментарии

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +//поставил выше, потому что не всплывает
Эх, я думал придумаешь как. Сделай функцию которая будет возвращать их тебе. Я просто хочу чтобы они не занимали место в начале файла, а их получать это уже пофиг

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +  getPostsPage(downloadInfo) {
Скорее `pageParams` или что-то типа того

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +    let promise = new Promise((resolve, reject) => {
Я просил сделать чтобы возвращался промис потому что с бекенда так будет. Тут можно просто сделать `Promise.resolve` и не надо никакие симулировать задержки или типа того. Просто чтобы интерфейс у метода был правильный (возвращаемый тип и параметры, чтобы когда тут будет реальный запрос на бэкенд не пришлось ничего менять)ю

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +      for (let i = 0; i < downloadInfo.take; i++) {
Просто посмотри `Array.slice` это то что тебе нужно.

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +    resultObj.skipped = realSkipped;
Эти значения можно и без циклов находить. Для получения списка воспользуйся `Array.slice`. Для получения остальных значений достаточно простой логики (например, если `pageParams.skip < Posts.length`, то логично что `skipped = pageParams.skip` и так далее. Сделай без цикелов, они тут не нужны

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +const Post = [
Влад уже писал про нейминг. Это реально очень важно. Когда проект большой и все называется как попало невозможно разобрать. Мы условились константы капсом, давай будем придерживаться правил. И я бы сделал `POSTS` раз уж это массив.

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +    //я думал ассинхронность кода, в том, чтобы знать реальное число записанных элементов
Не, промис тут просто чтобы когда здесь будет реальный запрос на бэкенд нам ничего не приходилось переделывать. То есть чтобы остальное приложение можно было разрабатывать как будто тут реальный запрос

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +let info = {
Не комитай лишнее. Тести, все правильно, но в пул реквест это не должно попадать. В пул реквестах должен быть готовый код чтобы нажать на мерж и все работает ничего менять не надо

2019-02-27 22:28 UTC, 5wag commented on src/services/apiService.js
> +/*export default service;*/
Чего закомменчено?

2019-02-27 23:41 UTC, Vlad160 commented on src/services/apiService.js
> +  getPostsPage(downloadInfo) {
Или params :)

2019-02-27 23:44 UTC, Vlad160 commented on src/services/apiService.js
> +    let promise = new Promise((resolve, reject) => {
Ещё хотелось бы напомнить о том, чтобы ты использовал `let` и `const` правильно

2019-03-11 09:18 UTC, r-karol requested changes

2019-03-11 09:18 UTC, 5wag commented on src/services/apiService.js
> +    finalObject.total = finalObject.taken + finalObject.skipped;
` = finalObject.length;`

2019-03-11 09:18 UTC, 5wag commented on src/services/apiService.js
> +    const takenPost = posts.slice(0, params.take);
Так а чего ты не скипаешь посты (не юзаешь `skip` из `params`)?
подумай хорошенько как тут правильно написать (посмотри еще раз как работает `Array.slice`)

2019-03-11 09:18 UTC, 5wag commented on src/services/apiService.js
> +    const finalObject = {};
Я бы сделал так что поля сразу тут сетаются, а не потом отдельно. Мне кажется так более секси

2019-03-11 09:18 UTC, 5wag commented on src/services/apiService.js
> +    const finalObject = {};
Но это на твой вкус

2019-04-11 19:42 UTC, DunaevViktor commented on src/services/apiService.js
> +    finalObject.total = finalObject.taken + finalObject.skipped;
не понял для чего это замечание

2019-04-12 18:24 UTC, 5wag commented on src/services/apiService.js
> +    finalObject.total = finalObject.taken + finalObject.skipped;
`finalObject.total` - это сколько всего элементов в базе данных
в нашем случае это `posts.length` (опечатка в моем коменте)

2019-04-12 18:49 UTC, r-karol requested changes
Поправь значение для total и будет четко

2019-04-13 19:51 UTC, r-karol approved these changes

2019-04-13 20:14 UTC, merged